---
- name: Install required dependencies
  apt:
    name:
      - libssl-dev
      - python3-pip
    state: present

- name: Install pyOpenSSL
  pip:
    name:
      - pyOpenSSL
    state: latest

- name: Create private key
  openssl_privatekey:
    owner: vault
    path: /etc/vault.d/vault.key
    size: 2048
    state: present
    type: RSA
  register: privatekey

- name: Create certificate signing request
  openssl_csr:
    common_name: MongoDB
    owner: vault
    path: /etc/vault.d/vault.csr
    privatekey_path: '{{ privatekey.filename }}'
    subject_alt_name: '{{ tls_subject_alt_name }}'
  register: csr

- name: Create self-signed certificate
  openssl_certificate:
    csr_path: '{{ csr.filename }}'
    owner: vault
    path: /etc/vault.d/vault.crt
    privatekey_path: '{{ privatekey.filename }}'
    provider: selfsigned
    state: present
  register: selfsigned

- name: Copy self-signed certificate to local CA certificates directory
  copy:
    content: '{{ lookup("file", selfsigned.filename) }}'
    dest: /usr/local/share/ca-certificates/vault.crt

- name: Update certificates
  command: update-ca-certificates

- name: Remove certificate signing request
  file:
    path: '{{ csr.filename }}'
    state: absent
