ca_common_name          = "mongodb.com"
ca_public_key_file_path = "/opt/vault/tls/ca.crt.pem"
common_name             = "mongodb.com"
dns_names               = ["vault.local"] # DO NOT CHANGE
ip_addresses            = ["127.0.0.1"]
organization_name       = "MongoDB"
owner                   = "vault"
private_key_file_path   = "/opt/vault/tls/vault.key.pem"
public_key_file_path    = "/opt/vault/tls/vault.crt.pem"
validity_period_hours   = 8760
