---
- name: Install unzip
  apt:
    name:
      - unzip
    state: present

- name: Download and install Vault
  unarchive:
    creates: /usr/local/bin/vault
    dest: /usr/local/bin
    remote_src: true
    src: https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip

- name: Create Vault user and group
  user:
    create_home: false
    home: /etc/vault.d
    name: vault
    shell: /bin/false
    state: present
    system: true

- name: Create Vault configuration directories
  file:
    group: vault
    owner: vault
    path: '{{ item }}'
    recurse: true
    state: directory
  with_items:
    - /etc/vault.d
    - /var/log/vault

- name: Grant Vault executable the ability to use the mlock syscall
  capabilities:
    capability: cap_ipc_lock+ep
    path: /usr/local/bin/vault
    state: present

- name: Copy Vault systemd unit file
  copy:
    dest: /etc/systemd/system/vault.service
    src: vault.service

# Vault encrypts data in transit and at rest, however it must still have sensitive data in memory to function. Risk of
# exposure should be minimized by disabling swap to prevent the operating system from paging sensitive data to disk
- name: Disable swap
  command: swapoff -a

- name: Copy logrotate configuration file
  copy:
    dest: /etc/logrotate.d/vault
    src: logrotate

- name: Create crontab entry for logrotate
  cron:
    job: logrotate -f /etc/logrotate.d/vault
    special_time: daily
