---
- name: Install unzip
  apt:
    name:
      - unzip
    state: present

- name: Create Vault user and group
  user:
    create_home: false
    name: vault
    state: present
    system: true

- name: Download and install Vault
  unarchive:
    creates: /usr/local/bin/vault
    dest: /usr/local/bin
    remote_src: true
    src: https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip

- name: Create Vault configuration directory
  file:
    path: /etc/vault.d
    state: directory

- name: Grant Vault executable the ability to use the mlock syscall
  capabilities:
    capability: cap_ipc_lock+ep
    path: /usr/local/bin/vault
    state: present

- name: Copy Vault systemd unit file
  copy:
    dest: /etc/systemd/system/vault.service
    src: vault.service
