---
- name: Download and install Amazon CloudWatch agent
  yum:
    name: https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
    state: present
  become: true
